[build]
  base    = "."
  command = "yarn build"
  publish = "build"
  functions = "build/fns"

[context.production]
  environment = { status = "live" }

[context.deploy-preview]
  environment = { status = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
